<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { useText } from '../i18n'
import catalogue from '../docs/api-generated.json'
import DropdownSelect from '../components/DropdownSelect.vue'
import CodeBlock from '../components/CodeBlock.vue'
const { locale } = useText()
const t = (zh:string,en:string,ja:string) => locale.value==='en'?en:locale.value==='ja'?ja:zh
const route = useRoute(), search = ref(''), filter = ref('all')
type Language = 'zh-TW'|'en'|'ja'
const lang = computed(() => locale.value as Language)
const id = computed(() => String(route.params.group??'')+'/'+String(route.params.slug??''))
const entry = computed(() => catalogue.entries.find(e=>e.id===id.value))
const isTypes = computed(() => route.params.group==='types')
const index = computed(() => !route.params.group)
const groups = catalogue.groups as Record<string,Record<Language,string>>
const results = computed(() => catalogue.entries.filter(e=>(filter.value==='all'||e.group===filter.value)&&`${e.name} ${e.module} ${e.summary[lang.value]}`.toLowerCase().includes(search.value.toLowerCase())))
const query = computed(() => ({ lang:locale.value, ...(route.query.framework?{framework:route.query.framework}:{}) }))
const link = (apiId:string) => ({ path:'/docs/api/'+apiId, query:query.value })
</script>
<template>
  <div class="docs-shell section-shell reading-workspace api-shell">
    <aside class="docs-sidebar api-sidebar"><RouterLink :to="{path:'/docs',query}" class="api-back">← {{ t('使用指南','Guides','ガイド') }}</RouterLink><p class="sidebar-group">API REFERENCE</p><RouterLink :to="{path:'/docs/api',query}" :class="{active:index}">{{ t('所有 API','All APIs','すべての API') }}</RouterLink><RouterLink :to="link('types')" :class="{active:isTypes}">{{ t('型別與常數','Types / constants','型・定数') }}</RouterLink><RouterLink :to="{path:'/docs',query:{...query,section:'studio'}}">Yuragi Studio</RouterLink><template v-for="(label,key) in groups" :key="key"><template v-if="key!=='types'"><p class="sidebar-group">{{ label[lang] }}</p><RouterLink v-for="item in catalogue.entries.filter(e=>e.group===key)" :key="item.id" :to="link(item.id)" :class="{active:entry?.id===item.id}" :aria-current="entry?.id===item.id?'page':undefined">{{ item.name }}{{ item.owner?.endsWith('Handle')?'()':'' }}</RouterLink></template></template></aside>
    <article class="docs-content api-content">
      <div class="docs-breadcrumb"><RouterLink :to="{path:'/docs',query}">{{ t('文件','Docs','ドキュメント') }}</RouterLink> / <RouterLink :to="{path:'/docs/api',query}">API</RouterLink><template v-if="entry"> / {{ groups[entry.group]?.[lang] }}</template></div>
      <template v-if="index"><div class="api-heading"><span class="api-kicker">YURAGI / {{ catalogue.version }}</span><h1>{{ t('所有 API，一個入口。','Every API, one place.','すべての API を、ひとつの入口に。') }}</h1><p class="docs-lead">{{ t('依函式、方法與框架查找。每個 API 都有獨立說明、實際型別與使用範例。','Find functions, methods and framework adapters with separate references, actual signatures and examples.','関数・メソッド・フレームワーク別に検索。個別説明・実際の型・使用例を確認できます。') }}</p></div><details class="api-entries"><summary>{{ t('套件公開入口','Public package entries','公開パッケージ入口') }}</summary><ul><li v-for="module in catalogue.modules" :key="module"><code>{{ module }}</code></li><li v-for="resource in catalogue.resources" :key="resource.module"><code>{{ resource.module }}</code> · {{ t('內附模型與圖片路徑，需依專案處理素材網址。','Bundled models/artwork; resolve their URLs in your project.','同梱モデル・画像。URL は利用側で解決します。') }}</li></ul></details><div class="api-search"><label><span>{{ t('搜尋 API','Search API','API を検索') }}</span><input v-model="search" type="search" placeholder="setPin, createPlayer, Vue…" /></label><DropdownSelect :label="t('分類','Category','分類')" :model-value="filter" :options="[{value:'all',label:t('所有分類','All categories','すべて')},...Object.entries(groups).filter(([key])=>key!=='types').map(([value,label])=>({value,label:label[lang]}))]" @update:model-value="v=>filter=v" /></div><p class="api-count">{{ results.length }} / {{ catalogue.entries.length }} {{ t('函式與方法','functions and methods','関数・メソッド') }} · <RouterLink :to="link('types')">{{ catalogue.types.length }} {{ t('型別與常數','types / constants','型・定数') }}</RouterLink></p><div class="api-results"><RouterLink v-for="item in results" :key="item.id" :to="link(item.id)" class="api-result"><span>{{ groups[item.group][lang] }}</span><h2>{{ item.name }} <small>↗</small></h2><p>{{ item.summary[lang] }}</p><code>{{ item.module }}</code></RouterLink></div><p v-if="!results.length" role="status">{{ t('找不到符合的 API。','No matching APIs.','一致する API がありません。') }}</p></template>
      <template v-else-if="isTypes"><h1>{{ t('型別與常數','Types and constants','型・定数') }}</h1><p class="docs-lead">{{ t('從套件公開入口擷取的完整 TypeScript 定義。','Complete TypeScript definitions from the public package entries.','公開入口から取得した TypeScript 定義です。') }}</p><nav class="api-type-index"><a v-for="type in catalogue.types" :key="type.module+type.name" :href="'#type-'+type.name">{{ type.name }}</a></nav><section v-for="type in catalogue.types" :id="'type-'+type.name" :key="type.module+type.name" class="api-type"><h2>{{ type.name }}</h2><code>{{ type.module }}</code><p v-if="type.description">{{ type.description }}</p><CodeBlock :code="type.definition" language="TypeScript" /></section></template>
      <template v-else-if="entry"><span class="api-kicker">{{ entry.module }}</span><h1>{{ entry.name }}{{ entry.owner?'()':'' }}</h1><p class="docs-lead">{{ entry.summary[lang] }}</p><h2>{{ t('型別簽名','Signature','型シグネチャ') }}</h2><CodeBlock :code="entry.signature" :language="entry.group==='vue'?'Vue / TypeScript':'TypeScript'" /><h2>{{ t('參數與預設值','Parameters and defaults','引数・初期値') }}</h2><div v-if="entry.parameters.length" class="table-scroll"><table><thead><tr><th>{{ t('參數','Parameter','引数') }}</th><th>{{ t('型別','Type','型') }}</th><th>{{ t('預設值與說明','Default / description','初期値・説明') }}</th></tr></thead><tbody><tr v-for="parameter in entry.parameters" :key="parameter.name"><td><code>{{ parameter.name }}{{ parameter.optional?'?':'' }}</code></td><td><code>{{ parameter.type }}</code></td><td><code v-if="parameter.default">{{ parameter.default }}</code><p>{{ parameter.description[lang] }}</p></td></tr></tbody></table></div><p v-else>{{ t('沒有位置參數。','No positional parameters.','位置引数なし。') }}</p><h2>{{ t('回傳值','Returns','戻り値') }}</h2><CodeBlock :code="entry.returns" language="TypeScript" /><h2>{{ t('行為、範圍與錯誤','Behavior, bounds and errors','動作・範囲・エラー') }}</h2><p class="api-behavior">{{ entry.notes[lang] }}</p><h2>{{ t('使用範例','Example','使用例') }}</h2><CodeBlock :code="entry.example??''" :language="entry.group==='vue'&&entry.name!=='getPlayer'?'Vue':'TypeScript'" /><p class="api-example-note">{{ t('範例中的 model、player、canvas 與 clip 需由已載入及驗證的資料提供。Vue／React 請在元件掛載後取得播放器。','Examples use a loaded/validated model, player, canvas or clip. Obtain players after mounting Vue/React components.','例の model・player・canvas・clip は読み込み・検証済みのデータを使用。プレイヤーはマウント後に取得します。') }}</p><h2>{{ t('相關 API','Related APIs','関連 API') }}</h2><div class="api-related"><RouterLink v-for="related in entry.related" :key="related" :to="link(related)">{{ related }}</RouterLink><RouterLink :to="link('types')">{{ t('型別與常數','Types / constants','型・定数') }}</RouterLink></div></template>
      <template v-else><h1>{{ t('找不到這個 API','API not found','API が見つかりません') }}</h1><RouterLink :to="{path:'/docs/api',query}">{{ t('返回所有 API','Back to all APIs','すべての API に戻る') }}</RouterLink></template>
    </article>
  </div>
</template>
<style scoped>
.api-sidebar{max-height:calc(100dvh - 110px);overflow-y:auto;scrollbar-width:thin}.api-sidebar a{font-size:12px!important;overflow-wrap:anywhere}.api-sidebar .sidebar-group{margin-top:22px}.api-back{margin-bottom:22px}.api-kicker{font-size:11px;letter-spacing:1.2px;color:#009fc7;overflow-wrap:anywhere}.api-heading h1{margin-top:16px}.api-search{display:grid;grid-template-columns:minmax(0,1fr) 210px;gap:18px;margin:32px 0 16px}.api-search label span{display:block;font-size:12px;color:#73869a;margin-bottom:8px}.api-search input{width:100%;min-height:48px;padding:10px 14px;border:1px solid #cfe4ee;border-radius:8px;font:inherit;font-size:14px;background:#f5fbff}.api-search input:focus{outline:2px solid #009fc7;outline-offset:2px}.api-count{font-size:12px;color:#73869a}.api-results{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:24px}.api-result{border:1px solid #dce9f0;border-radius:12px;padding:22px;text-decoration:none!important;background:white;display:flex;flex-direction:column}.api-result:hover{border-color:#009fc7;background:#f7fcff}.api-result>span{font-size:10px;color:#73869a}.api-result h2{font-family:ui-monospace,monospace;font-size:16px;margin:12px 0;overflow-wrap:anywhere}.api-result h2 small{float:right;color:#009fc7}.api-result p{font-size:12px;line-height:1.7;color:#60758a;margin:0 0 20px}.api-result>code{font-size:10px;margin-top:auto;overflow-wrap:anywhere}.api-type-index,.api-related{display:flex;flex-wrap:wrap;gap:8px}.api-type-index a,.api-related a{padding:6px 10px;font-size:12px;border:1px solid #dce9f0;border-radius:6px}.api-type{scroll-margin-top:100px;padding-top:28px}.api-type>code{font-size:12px}.api-behavior{white-space:pre-wrap;font-size:14px;line-height:1.9}.api-example-note{font-size:12px;color:#73869a}.api-content td code{font-size:12px;overflow-wrap:anywhere;white-space:normal}.api-content td p{font-size:12px;min-width:140px}.api-content .docs-breadcrumb a{color:inherit;text-decoration:none}@media(max-width:900px){.api-search{grid-template-columns:1fr}.api-results{grid-template-columns:1fr}.api-sidebar{max-height:none}.api-shell{display:block}.api-sidebar{display:flex!important;position:static!important;flex-wrap:wrap;gap:8px;padding:12px;margin-bottom:24px;border-bottom:1px solid #dce9f0}.api-sidebar .sidebar-group,.api-sidebar .sidebar-group~a:not(.active){display:none}.api-sidebar .api-back{margin:0}.api-sidebar>a{width:auto}.api-content{padding:0!important}}
</style>
