<script setup lang="ts">
import { useText } from '../i18n'
import CodeBlock from './CodeBlock.vue'
const { locale } = useText()
const t=(zh:string,en:string,ja:string)=>locale.value==='en'?en:locale.value==='ja'?ja:zh
const install=`# In the Yuragi checkout\nnpm run pack:lib\n\n# In your own project (use the actual generated tarball path)\nnpm install /path/to/yuragi/artifacts/yuragi-rig-0.2.0.tgz\nnpx yuragi studio --project ./my-character --out ./yuragi-output`
</script>
<template>
  <p class="docs-lead">{{ t('Agent 先標註原圖，再用本機工具編輯、檢測與交付。官網遊樂場持續提供展示與互動體驗。','Annotate with an agent, then edit, inspect and deliver in the local tool. The website playground remains available.','エージェントで原画を測定し、ローカルツールで編集・確認・出力します。サイトの遊び場も維持します。') }}</p>
  <h2>{{ t('安裝與啟動','Install and launch','インストール・起動') }}</h2><CodeBlock :code="install" language="Terminal" /><p>{{ t('目前使用本機套件，尚未宣稱 npm 發布。Studio 已隨套件預先建置，不需另裝 Vite。Node.js／npm 為必要環境，Python／Pillow 只用於 Agent 素材準備。','Use the local package; no npm publication is claimed. Studio is prebuilt in the package and needs no separate Vite installation. Node.js/npm are required; Python/Pillow are only needed for agent artwork preparation.','ローカルパッケージを使用。npm 公開は未確認です。Studio はビルド済みで Vite の追加導入は不要。Node.js/npm が必要で、Python/Pillow は素材準備用です。') }}</p>
  <h2>{{ t('角色資料夾','Character folder','キャラクターフォルダー') }}</h2><CodeBlock :code="'my-character/\n├── model.json\n├── texture.png\n├── analysis.json          # optional source records\n└── report.json            # optional preparation report'" language="Files" /><p>{{ t('模型圖片使用相對於 model.json 的本機路徑。來源尺寸、原圖留白及量測座標必須一致；換圖不會自動綁定。','Images use local paths relative to model.json. Source size, margins and measured coordinates must agree; replacing artwork does not create bindings.','画像は model.json 基準のローカル相対パスを使用。寸法・余白・座標の一致が必要で、画像変更だけではバインドされません。') }}</p>
  <h2>{{ t('編輯、檢測、交付','Edit, review, deliver','編集・確認・出力') }}</h2><ol><li>{{ t('在原圖座標上編輯控制點、區域、頭頸與眼睛；無效草稿保留最後有效預覽。','Edit pins, regions, head/neck and eyes in source coordinates. Invalid drafts retain the last valid preview.','原画座標で制御点・領域・頭首・目を編集。不正な草稿でも最後の有効な表示を保持。') }}</li><li>{{ t('逐項檢查中立、極值、反向、接縫及備援；任何模型修改都需重新驗收。','Observe neutral pose, extremes, reversal, seams and fallback. Model edits invalidate prior visual acceptance.','中立・極値・反転・接続・代替表示を確認。モデル変更後は再確認。') }}</li><li>{{ t('完成驗證與人工檢查後，輸出新版本資料夾，包含模型、素材、驗收報告及三種整合範例。','After validation and manual review, export a new folder with model, images, acceptance and Vue/React/vanilla examples.','検証・手動確認後、新しいフォルダーにモデル・画像・確認記録・各フレームワーク例を保存。') }}</li></ol>
  <p>{{ t('v1 共享網格可製作；v2 分層可檢測但不編輯附件或權重。原標註保留為歷史紀錄，Studio 不重做像素拆件、不補圖。','v1 shared surfaces are editable; v2 layers are inspection-only. Original annotations remain historical records; Studio does not re-extract pixels or create missing artwork.','v1 は編集可能、v2 は確認専用です。元の測定は履歴として保持し、ピクセルの再抽出・補完画像の生成は行いません。') }}</p>
  <h2>{{ t('命令選項','CLI options','CLI オプション') }}</h2><CodeBlock :code="'npx yuragi studio                    # start screen / bundled examples\nnpx yuragi studio --project ./rig    # load a character\nnpx yuragi studio --out ./exports    # output root (default: ./yuragi-output)\nnpx yuragi studio --port 4321        # choose a port (default: available port)\nnpx yuragi studio --no-open          # print URL without opening browser'" language="Terminal" /><p>{{ t('僅監聽 127.0.0.1。來源檔案不覆寫；草稿寫入輸出根目錄，每次交付建立新資料夾。','Listens only on 127.0.0.1. Source files are preserved; drafts live under the output root and each delivery creates a new folder.','127.0.0.1 のみで待機。元ファイルは保持し、草稿・出力は指定したルートへ保存します。') }}</p>
</template>
