<script setup lang="ts">
import { computed, ref, shallowRef, onMounted, onBeforeUnmount, nextTick, watch } from 'vue'
import { createPlayer, createLayeredPlayer, reviewPoses, faceReviewPoses, toCanvas } from '@yuragi/rig'
import type { RigPlayer, LayeredPlayer, RigSnapshot, LayeredSnapshot, Vec2, MouthShape } from '@yuragi/rig'
import type { StudioModel, StudioReview } from '../../../packages/rig/src/studio/document'
import { reviewChecks } from '../../../packages/rig/src/studio/document'
import type { StudioIssue } from '../../../packages/rig/src/studio/project'
import DropdownSelect from '../../site/src/components/DropdownSelect.vue'
import Icon from '../../site/src/components/Icon.vue'
import { geometry } from './geometry'
import logo from '../../site/public/images/brand/yuragi-katakana-web-v1.png'

type Locale = 'zh-TW' | 'en' | 'ja'
const locale = ref<Locale>('zh-TW')
const t = (zh: string, en: string, ja: string) => locale.value === 'en' ? en : locale.value === 'ja' ? ja : zh
interface Summary { currentVersion?: string; stage?: string; error?: string; versions: { id: string; label?: string; fingerprint?: string; ready: boolean; stale?: boolean; error?: string }[] }
interface Session { model: StudioModel | null; assets?: Record<string,string>; sourceFingerprint?: string; assetFingerprint?: string; versionId?: string; project?: Summary; records?: Record<string,unknown>; issues?: StudioIssue[]; output: string }
const session = shallowRef<Session>(), summary = shallowRef<Summary>(), canvas = ref<HTMLCanvasElement>(), overlay = ref<HTMLCanvasElement>(), stage = ref<HTMLElement>(), art = ref<HTMLElement>()
const model = computed(() => session.value?.model), size = computed(() => model.value?.version === 1 ? model.value.texture : model.value?.source)
const source = computed(() => { const m = model.value; return m ? session.value?.assets?.[m.version === 1 ? m.texture.src : m.source.fallback] : undefined })
const canvasStyle = computed(() => ({ aspectRatio: size.value ? `${size.value.width}/${size.value.height}` : '2/3' }))
const selection = ref(''), mode = ref<'original'|'neutral'|'motion'|'compare'>('neutral'), panel = ref<'preview'|'parts'|'review'>('preview')
const zoom = ref(1), pan = ref({ x: 0, y: 0 }), showMesh = ref(false), showAnnotations = ref(false), reduced = ref(false), busy = ref(false), failed = ref(false)
const message = ref(''), observation = ref(''), notes = ref(''), poseId = ref('neutral'), milliseconds = ref(0), pointer = ref<Vec2>([0,0]), sourcePoint = ref<Vec2>(), captured = ref<string>(), issues = ref<StudioIssue[]>([])
const checks = ref<Partial<Record<typeof reviewChecks[number],boolean>>>({}), snapshot = shallowRef<RigSnapshot|LayeredSnapshot>()
let player: RigPlayer|LayeredPlayer|undefined, raf = 0, last = 0, elapsed = 0, reportAt = 0, poll: ReturnType<typeof setInterval>|undefined, request = new AbortController(), loading: AbortController|undefined, media: MediaQueryList|undefined, generation = 0
let drag: { id: number; start: Vec2; pan: {x:number;y:number}; target: HTMLElement }|undefined
const api = async <T,>(path: string, body?: unknown): Promise<T> => {
  const token = document.querySelector<HTMLMetaElement>('meta[name="studio-token"]')?.content ?? ''
  const res = await fetch('/api/'+path,{method:body === undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Yuragi-Session':token},body:body === undefined?undefined:JSON.stringify(body),signal:request.signal})
  const data = await res.json(); if (!res.ok) throw new Error(data.error ?? 'Request failed'); return data
}
const graph = computed(() => model.value?.version === 1 ? geometry(model.value) : undefined)
const parts = computed(() => {
  const m=model.value;if(!m)return []
  return m.version===1 ? [
    ...m.pins.map(p=>({id:p.name,kind:t('控制點','Pin','制御点'),points:[[p.x,p.y]] as Vec2[],data:p})),
    ...(m.parts??[]).map(p=>({id:p.id,kind:t('柔性部件','Flexible part','柔軟パーツ'),points:p.polygon,data:p})),
    ...(m.surfaceRegions??[]).map(p=>({id:p.id,kind:t('綁定區域','Binding region','バインド領域'),points:p.polygon,data:p})),
  ] : m.attachments.map(a=>({id:a.id,kind:a.coverage==='complete'?t('完整素材','Complete artwork','完成素材'):t('僅可見像素','Visible pixels','可視ピクセル'),points:[[a.bounds[0],a.bounds[1]],[a.bounds[2],a.bounds[3]]] as Vec2[],data:a}))
})
const selected = computed(() => parts.value.find(p=>p.id===selection.value))
const stale = computed(() => summary.value?.versions.find(v=>v.id===session.value?.versionId)?.stale)
const newer = computed(() => summary.value?.versions.find(v=>v.id===summary.value?.currentVersion&&v.ready&&v.fingerprint!==session.value?.sourceFingerprint))
const versionOptions = computed(() => summary.value?.versions.filter(v=>v.ready).map(v=>({value:v.id,label:v.label??v.id}))??[])
const currentVersion = computed({get:()=>session.value?.versionId??'legacy',set:id=>{void switchVersion(id)}})
const poses = computed(() => {
  const m=model.value;return [...reviewPoses,...(m?.version===2&&m.face?faceReviewPoses().filter(p=>p.id.startsWith('eyes')?m.face!.eyes?.length===2:!!m.face!.mouth?.shapes[p.id.slice(6) as MouthShape]):[])]
})
const complete = computed(() => !!player&&!failed.value&&!stale.value&&reviewChecks.every(k=>checks.value[k])&&issues.value.every(i=>i.resolved))
const labels: Record<string,[string,string,string]> = {neutral:['中立還原','Neutral restoration','ニュートラル'],directions:['上下左右','Four directions','上下左右'],corners:['四個角落','Four corners','四隅'],reversal:['快速反向','Rapid reversal','急な反転'],eyes:['眼睛／眼線（不適用時註明）','Eyes / eye lines (note N/A)','目・目線（該当なしは記録）'],seams:['頭頸接縫','Head / neck seams','頭・首の接続'],hair:['髮根與部件根部','Hair / part roots','髪・パーツの根元'],clipping:['邊緣與裁切','Edges / clipping','端・クリッピング'],contacts:['持物與接觸','Props / contacts','持ち物・接触'],'reduced-motion':['減少動態','Reduced motion','動作軽減'],fallback:['原畫備援','Artwork fallback','原画フォールバック']}
function stop(){cancelAnimationFrame(raf);last=0;player?.pause()}
function report(){if(!player)return;snapshot.value=player.getSnapshot();milliseconds.value=elapsed;drawOverlay()}
function drawOverlay(){const c=overlay.value;if(!c||!size.value)return;c.width=size.value.width;c.height=size.value.height;const ctx=c.getContext('2d');if(!ctx)return
  const point=(p:Vec2)=>[p[0]*c.width,p[1]*c.height] as Vec2
  if(showMesh.value&&player){const mesh=player.getMeshSnapshot();ctx.strokeStyle='#008bb780';ctx.lineWidth=1;ctx.beginPath();for(let i=0;i<mesh.indices.length;i+=3)for(let j=0;j<4;j++){const v=mesh.indices[i+j%3]*2,p=point([mesh.positions[v],mesh.positions[v+1]]);j?ctx.lineTo(...p):ctx.moveTo(...p)}ctx.stroke()}
  if(showAnnotations.value){ctx.strokeStyle='#006a94';ctx.lineWidth=2;for(const outline of graph.value?.outlines??[]){ctx.beginPath();outline.points.forEach((p,i)=>i?ctx.lineTo(...point(p)):ctx.moveTo(...point(p)));if(outline.closed)ctx.closePath();ctx.stroke()}}
  if(selected.value){ctx.strokeStyle='#e49432';ctx.lineWidth=3;ctx.beginPath();selected.value.points.forEach((p,i)=>i?ctx.lineTo(...point(p)):ctx.moveTo(...point(p)));if(selected.value.points.length>2)ctx.closePath();ctx.stroke();for(const p of selected.value.points){ctx.beginPath();ctx.arc(...point(p),4,0,Math.PI*2);ctx.fillStyle='#e49432';ctx.fill()}}
}
function tick(now:number){if(!player||!snapshot.value?.playing||reduced.value)return;raf=requestAnimationFrame(tick);if(document.hidden){last=0;return}const delta=last?Math.min(now-last,50):1000/60;last=now;elapsed+=delta;player.advance(delta);if(now-reportAt>=100){reportAt=now;report()}}
function play(){if(!player||reduced.value)return;stop();player.play();snapshot.value=player.getSnapshot();raf=requestAnimationFrame(tick)}
function neutral(){stop();player?.reset();elapsed=0;pointer.value=[0,0];poseId.value='neutral';report()}
async function install(next:Session){const own=++generation;stop();loading?.abort();player?.destroy();player=undefined;session.value=next;summary.value=next.project;issues.value=next.issues??[];checks.value={};captured.value=undefined;failed.value=false;selection.value='';elapsed=0;mode.value='neutral';await nextTick();if(own!==generation||!next.model||!canvas.value)return
  const m=structuredClone(next.model),assets=next.assets??{};if(m.version===1)m.texture.src=assets[m.texture.src];else{m.source.fallback=assets[m.source.fallback];m.atlases.forEach(a=>a.src=assets[a.src])}
  loading=new AbortController();try{const created=m.version===1?await createPlayer({canvas:canvas.value,model:m,autoplay:false,manual:true,signal:loading.signal,onError:e=>{failed.value=true;message.value=e.message;stop()}}):await createLayeredPlayer({canvas:canvas.value,model:m,autoplay:false,manual:true,signal:loading.signal,onError:e=>{failed.value=true;message.value=e.message;stop()}});if(own!==generation){created.destroy();return}player=created;neutral()}catch(e){if(own===generation){failed.value=true;message.value=String(e)}}
}
async function switchVersion(id:string){busy.value=true;try{await install(await api<Session>('version',{versionId:id}))}catch(e){message.value=String(e)}finally{busy.value=false}}
async function example(){busy.value=true;try{await install(await api<Session>('example',{name:'mirea'}))}catch(e){message.value=String(e)}finally{busy.value=false}}
function setMode(next:typeof mode.value){mode.value=next;if(next==='neutral'||next==='original')neutral();else play()}
function fit(){zoom.value=1;pan.value={x:0,y:0}}
function fitPart(){const points=selected.value?.points;if(!points?.length)return;const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);const extent=Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys),.12);zoom.value=Math.min(8,Math.max(1,.75/extent));const w=art.value?.clientWidth??300,h=art.value?.clientHeight??450;pan.value={x:(.5-(Math.min(...xs)+Math.max(...xs))/2)*w*zoom.value,y:(.5-(Math.min(...ys)+Math.max(...ys))/2)*h*zoom.value}}
function wheel(e:WheelEvent){zoom.value=Math.max(.25,Math.min(8,zoom.value*Math.exp(-Math.max(-200,Math.min(200,e.deltaY))*.002)))}
function point(e:PointerEvent):Vec2|undefined{const box=art.value?.getBoundingClientRect();if(!box)return;return [Math.max(0,Math.min(1,(e.clientX-box.left)/box.width)),Math.max(0,Math.min(1,(e.clientY-box.top)/box.height))]}
function down(e:PointerEvent){const p=point(e);if(p)sourcePoint.value=p;if(e.button!==0)return;const target=e.currentTarget as HTMLElement;target.setPointerCapture(e.pointerId);drag={id:e.pointerId,start:[e.clientX,e.clientY],pan:{...pan.value},target}}
function move(e:PointerEvent){if(drag?.id===e.pointerId){pan.value={x:drag.pan.x+e.clientX-drag.start[0],y:drag.pan.y+e.clientY-drag.start[1]};return}if(mode.value==='motion'||mode.value==='compare'){const p=point(e);if(p){pointer.value=[p[0]-.5,p[1]-.5];player?.setPointer(...pointer.value)}}}
function end(e:PointerEvent){if(drag?.id===e.pointerId){if(drag.target.hasPointerCapture(e.pointerId))drag.target.releasePointerCapture(e.pointerId);drag=undefined}if(e.pointerType==='touch'){pointer.value=[0,0];player?.setPointer(0,0)}}
function key(e:KeyboardEvent){const values:Record<string,Vec2>={ArrowLeft:[-.5,0],ArrowRight:[.5,0],ArrowUp:[0,-.5],ArrowDown:[0,.5],Escape:[0,0]};if(values[e.key]){e.preventDefault();pointer.value=values[e.key];player?.setPointer(...pointer.value);report()}}
async function runPose(id:string){if(!player)return;stop();mode.value='neutral';player.reset();elapsed=0;const pose=poses.value.find(p=>p.id===id);if(!pose)return;for(const step of pose.sequence){pointer.value=step.pointer;player.setPointer(...step.pointer);if(step.face&&'setFace'in player)player.setFace(step.face);player.advance(step.milliseconds);elapsed+=step.milliseconds}poseId.value=id;report()}
async function record(){stop();report();const c=canvas.value;if(!c)return;if(mode.value==='original'||failed.value){const image=new Image();image.src=source.value!;await image.decode();const scratch=document.createElement('canvas');scratch.width=image.width;scratch.height=image.height;scratch.getContext('2d')!.drawImage(image,0,0);captured.value=scratch.toDataURL('image/png')}else captured.value=c.toDataURL('image/png');panel.value='review'}
async function saveIssue(){if(!captured.value||!observation.value.trim())return;busy.value=true;try{const result=await api<{path:string;issue:StudioIssue}>('issues',{sourceFingerprint:session.value?.sourceFingerprint,partId:selection.value||undefined,pose:poseId.value,milliseconds:milliseconds.value,pointer:pointer.value,sourcePoint:sourcePoint.value,snapshot:snapshot.value,observation:observation.value,screenshot:captured.value});issues.value=[...issues.value,result.issue];checks.value={};message.value=result.path;observation.value='';captured.value=undefined}catch(e){message.value=String(e)}finally{busy.value=false}}
async function resolveIssue(issue:StudioIssue){try{const result=await api<{issues:StudioIssue[]}>('issue-status',{sourceFingerprint:session.value?.sourceFingerprint,id:issue.id,resolved:!issue.resolved});issues.value=result.issues;checks.value={}}catch(e){message.value=String(e)}}
async function deliver(){if(!complete.value||!model.value)return;busy.value=true;try{const review:StudioReview={fingerprint:session.value!.sourceFingerprint!,checks:checks.value,notes:notes.value};const result=await api<{path:string}>('export',{sourceFingerprint:session.value?.sourceFingerprint,model:model.value,review,changes:[]});message.value=result.path}catch(e){message.value=String(e)}finally{busy.value=false}}
function motionChange(){reduced.value=!!media?.matches;if(reduced.value)neutral()}
watch([selection,showMesh,showAnnotations],()=>drawOverlay())
onMounted(async()=>{media=matchMedia('(prefers-reduced-motion: reduce)');motionChange();media.addEventListener('change',motionChange);try{await install(await api<Session>('session'))}catch(e){message.value=String(e)}poll=setInterval(()=>{if(!document.hidden)void api<Summary>('summary').then(next=>{summary.value=next}).catch(e=>{message.value=String(e)})},2000)})
onBeforeUnmount(()=>{generation++;stop();request.abort();loading?.abort();player?.destroy();if(poll)clearInterval(poll);media?.removeEventListener('change',motionChange)})
</script>

<template>
  <header class="studio-header"><a class="brand" href="#" @click.prevent="fit"><img :src="logo" alt="Yuragi" /><span>Studio</span></a><nav :aria-label="t('工作流程','Workflow','ワークフロー')"><span>01 {{ t('Agent 製作','Agent preparation','エージェント制作') }}</span><span class="active">02 {{ t('預覽與驗收','Preview & review','プレビュー・確認') }}</span><span>03 {{ t('專案整合','Integration','組み込み') }}</span></nav><DropdownSelect v-model="locale" :label="t('語言','Language','言語')" :options="[{value:'zh-TW',label:'繁體中文'},{value:'en',label:'English'},{value:'ja',label:'日本語'}]" inline /></header>
  <div v-if="message" role="status" class="notice">{{ message }}<button @click="message=''" :aria-label="t('關閉通知','Dismiss','閉じる')">×</button></div>
  <main v-if="!model" class="welcome"><span class="eyebrow">YURAGI STUDIO</span><h1>{{ t('讓 Agent 製作，\n在這裡看見角色動起來。','Prepare with an agent.\nSee your character move here.','エージェントで制作。\nここで動きを確認。') }}</h1><p>{{ t('從原圖標註、拆件到模型綁定，交給 Skill 與本機 Python 工具。Studio 幫你比較原圖、測試動態並記錄修正需求。','Use the Skill and local Python tools to annotate, extract and bind artwork. Studio compares, tests and records issues.','Skill とローカル Python で測定・切り出し・バインド。Studio で比較・テスト・問題を記録します。') }}</p><button class="primary" :disabled="busy" @click="example"><Icon name="play" :size="16" />{{ t('預覽海月 Mirea','Preview Mirea','海月 Mirea を見る') }}</button><div class="start-guide"><h2>{{ t('開啟 Agent 製作的模型','Open an agent-built model','制作したモデルを開く') }}</h2><code>npx yuragi studio --project ./my-character --out ./yuragi-output</code><p>{{ t('請 Agent 先讀取 yuragi-rig-spec，再完成 inspect → extract → build。只更換圖片不會產生綁定。','Ask the agent to read yuragi-rig-spec and run inspect → extract → build. Replacing an image does not create a rig.','yuragi-rig-spec を読み、inspect → extract → build を実行。画像変更だけではバインドされません。') }}</p></div></main>
  <main v-else>
    <section class="project-bar"><div><span class="eyebrow">{{ model.version===1?'SHARED SURFACE':'LAYERED MODEL' }}</span><h1>{{ model.name }}</h1><p>{{ size?.width }} × {{ size?.height }} · {{ session?.versionId }} · {{ t('唯讀模型預覽','Read-only model preview','読み取り専用プレビュー') }}</p></div><div class="actions"><button @click="example" :disabled="busy">{{ t('海月範例','Mirea sample','海月サンプル') }}</button><button @click="record" :disabled="busy||!source"><Icon name="pin" :size="16" />{{ t('記錄問題','Record issue','問題を記録') }}</button><button class="primary" @click="deliver" :disabled="busy||!complete">{{ t('交付到專案','Deliver to project','プロジェクトへ出力') }}</button></div></section>
    <div v-if="newer" class="notice">{{ t('Agent 已完成新版模型。','A new version is ready.','新しいモデルが完成しました。') }}<button @click="switchVersion(newer.id)">{{ t('載入新版','Load new version','新版を開く') }} {{ newer.id }}</button></div>
    <div v-if="stale||summary?.error" class="notice warning">{{ summary?.error??t('製作輸入已變更，需要 Agent 重新抽取／編譯。保留上一個有效预覽。','Authoring inputs changed. Ask the agent to extract / compile again. Last valid preview retained.','入力が変わりました。再抽出・コンパイルが必要です。最後のプレビューを保持。') }}</div>
    <div class="mobile-tabs"><button v-for="tab in ['preview','parts','review'] as const" :key="tab" :class="{active:panel===tab}" @click="panel=tab">{{ tab==='preview'?t('預覽','Preview','プレビュー'):tab==='parts'?t('部件','Parts','パーツ'):t('驗收','Review','確認') }}</button></div>
    <div class="workspace" :class="'mobile-'+panel">
      <aside class="parts-panel"><h2>{{ t('專案與部件','Project & parts','プロジェクト・パーツ') }}</h2><DropdownSelect v-if="versionOptions.length" v-model="currentVersion" :label="t('模型版本','Model version','モデル版')" :options="versionOptions" /><div class="stage-state"><span class="status-dot"></span>{{ summary?.stage??'compiled' }}</div><p class="hint">{{ model.version===1?t('裁片為製作素材；播放器使用完整原圖。','Extracts are authoring assets; playback uses the full source.','切り出しは制作素材。再生には原画全体を使用。'):t('附件依模型順序繪製。僅可見像素的部件仍需遮擋補圖。','Attachments draw in model order. Visible-only parts still need occluded artwork.','モデル順で描画。可視ピクセルのみのパーツは補完が必要です。') }}</p><button class="part" v-for="part in parts" :key="part.id" :class="{selected:selection===part.id}" @click="selection=part.id"><Icon name="layers" :size="15" /><span>{{ part.id }}<small>{{ part.kind }}</small></span></button><button v-if="selected" class="fit-part" @click="fitPart">{{ t('放大選取部件','Fit selected part','選択パーツを拡大') }}</button></aside>
      <section class="preview-panel"><div class="preview-toolbar"><div class="mode-tabs"><button v-for="v in ['original','neutral','motion','compare'] as const" :key="v" :class="{active:mode===v}" @click="setMode(v)">{{ v==='original'?t('原圖','Source','原画'):v==='neutral'?t('中立','Neutral','ニュートラル'):v==='motion'?t('動畫','Motion','動き'):t('並排比較','Compare','比較') }}</button></div><div class="toggles"><button :aria-pressed="showMesh" @click="showMesh=!showMesh">{{ t('網格','Mesh','メッシュ') }}</button><button :aria-pressed="showAnnotations" @click="showAnnotations=!showAnnotations">{{ t('標註','Annotations','測定') }}</button></div></div>
        <div class="comparison" :class="{split:mode==='compare'}"><div v-if="mode==='compare'" class="reference"><span>{{ t('原始插畫','Source artwork','原画') }}</span><img :src="source" :alt="model.name" /></div><div ref="stage" class="canvas-stage" tabindex="0" :aria-label="t('角色預覽，方向鍵控制姿態，拖曳平移','Character preview: arrows control pose, drag pans','矢印でポーズ、ドラッグで移動')" @wheel.prevent="wheel" @pointerdown="down" @pointermove="move" @pointerup="end" @pointercancel="end" @keydown="key"><div ref="art" class="artwork" :style="{...canvasStyle,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}"><img :src="source" :alt="model.name" class="fallback" :class="{hidden:mode!=='original'&&!failed}" /><canvas ref="canvas" class="player-canvas" :class="{hidden:mode==='original'||failed}" aria-hidden="true" /><canvas ref="overlay" class="overlay" aria-hidden="true" /></div></div></div>
        <div class="preview-controls"><div><button @click="snapshot?.playing?(stop(),report()):play()" :disabled="reduced||failed">{{ snapshot?.playing?t('暫停','Pause','停止'):t('播放','Play','再生') }}</button><button @click="neutral">{{ t('回正','Reset pose','ポーズを戻す') }}</button></div><div class="zoom"><button @click="zoom=Math.max(.25,zoom/1.25)" :aria-label="t('縮小','Zoom out','縮小')">−</button><output>{{ Math.round(zoom*100) }}%</output><button @click="zoom=Math.min(8,zoom*1.25)" :aria-label="t('放大','Zoom in','拡大')">＋</button><button @click="fit">{{ t('適合視窗','Fit view','全体表示') }}</button></div></div><p class="hint caption">{{ reduced?t('系統已啟用減少動態，顯示原始姿態。','System reduced motion is enabled.','動作軽減が有効です。'):t('移動游標／方向鍵測試；拖曳平移，滾輪縮放。','Move pointer / use arrows to test; drag to pan, scroll to zoom.','ポインター・矢印でテスト。ドラッグで移動、スクロールで拡大。') }}</p>
      </section>
      <aside class="review-panel"><h2>{{ t('測試與問題','Tests & issues','テスト・問題') }}</h2><p class="hint">{{ t('測試完成不代表視覺驗收通過。','Running tests does not grant visual acceptance.','テスト実行と見た目の合格は別です。') }}</p><div class="pose-grid"><button v-for="pose in poses" :key="pose.id" :class="{selected:poseId===pose.id}" @click="runPose(pose.id)" :disabled="reduced&&pose.id!=='neutral'||failed">{{ pose.id }}</button></div><div class="review-command"><h3>{{ t('固定姿勢圖集','Rendered pose sheet','固定ポーズ一覧') }}</h3><code>npx yuragi review --project ./my-character --out ./review-v1</code><small>{{ t('使用本機 Playwright；Agent 讀取圖集並檢查細節。','Uses local Playwright; the agent reads the rendered sheet.','ローカル Playwright で描画し、エージェントが確認します。') }}</small></div>
        <details v-if="selected"><summary>{{ selected.id }}</summary><pre>{{ JSON.stringify(selected.data,null,2) }}</pre></details>
        <div v-if="model.version===2&&!model.face" class="material-note">{{ t('眼嘴尚未配置。請另行提供眼皮底圖、半閉／閉眼及嘴型素材，再交由 Agent 綁定。','Face is not authored. Supply eyelid skin, half / closed eyes and mouth variants for agent binding.','顔は未設定。まぶた、半閉・閉眼、口形素材を提供してください。') }}</div>
        <div v-if="captured" class="issue-form"><h3>{{ t('這個姿勢的問題','Issue in this pose','このポーズの問題') }}</h3><img :src="captured" :alt="t('問題截圖','Issue capture','問題画像')" /><p class="hint">{{ selection||'whole-character' }} · {{ poseId }} · {{ Math.round(milliseconds) }}ms</p><label>{{ t('觀察與修正需求','Observation / requested correction','観察・修正内容') }}<textarea v-model="observation" rows="3" /></label><button class="primary" @click="saveIssue" :disabled="busy||!observation.trim()">{{ t('保存問題檔','Save issue file','問題ファイルを保存') }}</button><button @click="captured=undefined">{{ t('取消','Cancel','キャンセル') }}</button></div>
        <div class="issue-list" v-if="issues.length"><h3>{{ t('問題報告','Issues','問題') }}</h3><article v-for="issue in issues" :key="issue.id"><span>{{ issue.partId??'whole-character' }} · {{ issue.pose }}</span><p>{{ issue.observation }}</p><button @click="resolveIssue(issue)">{{ issue.resolved?t('重新標記待修正','Reopen issue','再確認'):t('已親自確認修正','Confirm resolved','修正を確認') }}</button></article></div>
        <details class="acceptance"><summary>{{ t('視覺驗收與交付','Visual acceptance & delivery','見た目の確認・出力') }}</summary><label v-for="check in reviewChecks" :key="check" class="check"><input type="checkbox" v-model="checks[check]" />{{ t(...labels[check]) }}</label><label>{{ t('觀察、裝置與未測項目','Observations, devices, untested cases','観察・端末・未確認項目') }}<textarea v-model="notes" rows="3" /></label></details><details v-if="snapshot"><summary>{{ t('執行診斷','Runtime diagnostics','実行情報') }}</summary><pre>{{ JSON.stringify(snapshot.diagnostics,null,2) }}</pre></details>
      </aside>
    </div>
  </main>
  <footer><span>Yuragi Studio · {{ t('Agent 製作，本機預覽','Agent preparation · local preview','エージェント制作・ローカル確認') }}</span><span>TypeScript / Vue / React</span></footer>
</template>
