/** Examples consume the exported JSON, including its source-relative asset URLs. */
export function integrationExamples(layered: boolean) {
  const validator = layered ? 'validateLayeredModel' : 'validateModel'
  const factory = layered ? 'createLayeredPlayer' : 'createPlayer'
  const component = layered ? 'YuragiLayeredCharacter' : 'YuragiCharacter'
  const type = layered ? 'LayeredModel' : 'RigModel'
  const urls = layered
    ? "model.source.fallback = new URL(model.source.fallback, modelUrl).href\n  for (const atlas of model.atlases) atlas.src = new URL(atlas.src, modelUrl).href"
    : 'model.texture.src = new URL(model.texture.src, modelUrl).href'
  const loader = `import { ${validator} } from '@z7589xxz758/yuragi'\nexport async function loadModel(modelUrl: string, signal: AbortSignal) {\n  const response = await fetch(modelUrl, { signal })\n  if (!response.ok) throw new Error('Model HTTP ' + response.status)\n  const model: unknown = await response.json()\n  ${validator}(model)\n  ${urls}\n  return model\n}\n`
  return {
    'load-model.ts': loader,
    'Character.vue': `<script setup lang="ts">\nimport { onMounted, onBeforeUnmount, shallowRef, ref } from 'vue'\nimport { ${component} } from '@z7589xxz758/yuragi/vue'\nimport type { ${type} } from '@z7589xxz758/yuragi'\nimport { loadModel } from './load-model'\nconst model = shallowRef<${type}>(), error = ref('')\nconst controller = new AbortController()\nonMounted(async () => { try { const loaded = await loadModel(new URL('/models/character/model.json', location.href).href, controller.signal); if (!controller.signal.aborted) model.value = loaded } catch (e) { if (!controller.signal.aborted) error.value = String(e) } })\nonBeforeUnmount(() => controller.abort())\n</script>\n<template>\n  <${component} v-if="model" :model="model" reduced-motion="respect" alt="Character" @error="error = $event.message" />\n  <p v-else role="status">{{ error || 'Loading character…' }}</p>\n</template>\n`,
    'Character.tsx': `import { useEffect, useState } from 'react'\nimport { ${component} } from '@z7589xxz758/yuragi/react'\nimport type { ${type} } from '@z7589xxz758/yuragi'\nimport { loadModel } from './load-model'\nexport default function Character() {\n  const [model, setModel] = useState<${type}>(), [error, setError] = useState('')\n  useEffect(() => {\n    const controller = new AbortController()\n    void loadModel(new URL('/models/character/model.json', location.href).href, controller.signal).then(value => { if (!controller.signal.aborted) setModel(value) }).catch(e => { if (!controller.signal.aborted) setError(String(e)) })\n    return () => controller.abort()\n  }, [])\n  return model ? <${component} model={model} reducedMotion="respect" alt="Character" onError={e => setError(e.message)} /> : <p role="status">{error || 'Loading character…'}</p>\n}\n`,
    'vanilla.ts': `import { ${factory} } from '@z7589xxz758/yuragi'\nimport { loadModel } from './load-model'\nexport async function mountCharacter(canvas: HTMLCanvasElement, fallback: HTMLImageElement, modelUrl: string, signal: AbortSignal) {\n  const model = await loadModel(modelUrl, signal)\n  fallback.src = ${layered ? 'model.source.fallback' : 'model.texture.src'}\n  fallback.hidden = false\n  canvas.hidden = true\n  try {\n    const player = await ${factory}({ canvas, model, signal, reducedMotion: 'respect', onError: () => { fallback.hidden = false; canvas.hidden = true } })\n    if (signal.aborted) { player.destroy(); return () => {} }\n    fallback.hidden = true; canvas.hidden = false\n    return () => { player.destroy(); canvas.hidden = true; fallback.hidden = false }\n  } catch (error) { fallback.hidden = false; canvas.hidden = true; throw error }\n}\n// Use an AbortController and call abort() on navigation/unmount.\n// Place canvas at left/top -12%, width/height 124% inside the source-aspect container.\n`,
    'README.md': '# Character integration\n\nCopy this folder’s model.json and assets/ to public/models/character in your project. Copy the selected example and load-model.ts into your source directory. Install the locally packed @z7589xxz758/yuragi package; Vue and React are optional, separately imported adapters.\n\nThe adapters show the source artwork while loading and on WebGL failure, respect reduced motion, cancel pending loads and release resources on unmount. The vanilla example requires a source-aspect wrapper with an overscanned canvas (left/top -12%, width/height 124%) and an image fallback; abort its controller and call the returned cleanup on unmount.\n\nRead acceptance.json for observations and untested cases. Original annotations are historical source records, not re-extracted or re-certified by Studio edits. Artwork rights remain separate from the library license.\n',
  }
}
